### ISSUE TITLE
Sample project looks to be missing

### ISSUE THREAD

**Issue by abdu292** [marcusts/Com.MarcusTS.SmartDI#1]
Hi @marcusts Thanks for all the work on this. I am a Autofac user at this point, however really interested to start using your tools. I would like to see a SIMPLE, runnable sample Xamarin.Forms project implemented your tools end to end. One looks to be missing from this repo. I tried using the old repo "SafeDiContainer" but the sample doesn't compile and the project structure looks to be 
a little odd. Thanks again for all your work.

**Comment by marcusts** [comment]
Hi, I pushed some more repositories for you, including the SampleApp.

Stephen

**Comment by abdu292** [comment]
Wow, that was quick. Thanks @marcusts. I am looking on to this.
Any reason you push the solution files to a different repository than the original?

**Comment by marcusts** [comment]
Hi, yes, the Com.MarcusSTS.SmsrtDI must remain as small as possible so it
can be included in solutions as a focused library.  Most programmers object
to having their libraries loaded with miscellaneous support files.

Sorry for the hassle...

Stephen

**Comment by abdu292** [comment]
I see what you are saying. Thanks for the response!
